services:
  frontend:
    build:
      context: frontend
      target: development
    ports:
      - 3000:5173
    stdin_open: true
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    restart: always
    networks:
      - react-express

networks:
  react-express:
